locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "First-year PhD candidate at HKUST NLP Group"
url: "https://dmezalei-ci.github.io"
baseurl: "/LJT-Homepage"
repository: "dmezalei-ci/LJT-Homepage"

author:
  name: "Junteng Liu"
  avatar: false
  bio: "First-year PhD candidate at HKUST NLP Group"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

breadcrumbs: false
read_more: "disabled"
comments:
  provider:
atom_feed:
  hide: true

include:
  - _pages
  - files

collections:
  publications:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
